<?php 
function ip_info($ip = NULL, $purpose = "location", $deep_detect = TRUE) {
    $output = NULL;
    if (filter_var($ip, FILTER_VALIDATE_IP) === FALSE) {
        $ip = $_SERVER["REMOTE_ADDR"];
        if ($deep_detect) {
            if (filter_var(@$_SERVER['HTTP_X_FORWARDED_FOR'], FILTER_VALIDATE_IP))
                $ip = $_SERVER['HTTP_X_FORWARDED_FOR'];
            if (filter_var(@$_SERVER['HTTP_CLIENT_IP'], FILTER_VALIDATE_IP))
                $ip = $_SERVER['HTTP_CLIENT_IP'];
        }
    }
    $purpose    = str_replace(array("name", "\n", "\t", " ", "-", "_"), NULL, strtolower(trim($purpose)));
    $support    = array("country", "countrycode", "state", "region", "city", "location", "address");
    $continents = array(
        "AF" => "Africa",
        "AN" => "Antarctica",
        "AS" => "Asia",
        "EU" => "Europe",
        "OC" => "Australia (Oceania)",
        "NA" => "North America",
        "SA" => "South America"
    );
    if (filter_var($ip, FILTER_VALIDATE_IP) && in_array($purpose, $support)) {
        $ipdat = @json_decode(file_get_contents("http://www.geoplugin.net/json.gp?ip=" . $ip));
        if (@strlen(trim($ipdat->geoplugin_countryCode)) == 2) {
            switch ($purpose) {
                case "location":
                    $output = array(
                        "city"           => @$ipdat->geoplugin_city,
                        "state"          => @$ipdat->geoplugin_regionName,
                        "country"        => @$ipdat->geoplugin_countryName,
                        "country_code"   => @$ipdat->geoplugin_countryCode,
                        "continent"      => @$continents[strtoupper($ipdat->geoplugin_continentCode)],
                        "continent_code" => @$ipdat->geoplugin_continentCode
                    );
                    break;
                case "address":
                    $address = array($ipdat->geoplugin_countryName);
                    if (@strlen($ipdat->geoplugin_regionName) >= 1)
                        $address[] = $ipdat->geoplugin_regionName;
                    if (@strlen($ipdat->geoplugin_city) >= 1)
                        $address[] = $ipdat->geoplugin_city;
                    $output = implode(", ", array_reverse($address));
                    break;
                case "city":
                    $output = @$ipdat->geoplugin_city;
                    break;
                case "state":
                    $output = @$ipdat->geoplugin_regionName;
                    break;
                case "region":
                    $output = @$ipdat->geoplugin_regionName;
                    break;
                case "country":
                    $output = @$ipdat->geoplugin_countryName;
                    break;
                case "countrycode":
                    $output = @$ipdat->geoplugin_countryCode;
                    break;
            }
        }
    }
    return $output;
}

$oklen=ip_info("Visitor", "Country Code");
$oklen="DE";
if ($oklen=="HR" or $oklen=="BA" or $oklen=="RS" or $oklen=="SI"){
	$naslov="Sustav za rezervaciju sportskih terena";
	$drzava="images/cro2.png";
	$ind001="Korisničko ime i zaporka nisu ispravni ili je administrator zabranio pristup.";
	$ind002="Korisničko ime i zaporka se ne podudaraju. Probajte ponovo ili provjerite kod tajnika kluba.";
	$ind003="Popunite korisničko ime i zaporku.";
	$ind004="Korisničko ime";
	$ind004a="Upiši Vaše korisničko ime";
	$ind005="Pritisnuti za ulaz u sustav za registrirane korisnike";
	$ind006="Zaporka";
	$ind006a="Upiši Vašu zaporku";
	$ind007="Prijava";
	$ind020="Polazna";
	$ind021="Registriraj se";
	$ind022="Cjenik";
	$ind022a="Pogodnosti";
	$ind022b="Prednosti";
	$ind023="Kontakt";
	$ind024="Izvrši prijavu";
	$ind025="Pogodnosti Sportbooking sustava rezervacija sportskih terena:";
	$ind026a="Za klubove";
	$ind026a1="<i style='font-size:14px;color:#df691a;' class='fa fa-caret-right'></i>&nbsp; Snažan alat za upravljanje klubom i terenima";
	$ind026a2="<i style='font-size:14px;color:#df691a;' class='fa fa-caret-right'></i>&nbsp; Trenutni uvid (ne)zauzetosti sportskih terena";
	$ind026a3="<i style='font-size:14px;color:#df691a;' class='fa fa-caret-right'></i>&nbsp; Evidencija i vođenje članstva";
	$ind026a4="<i style='font-size:14px;color:#df691a;' class='fa fa-caret-right'></i>&nbsp; Naplata korištenja terena";
	$ind026a5="<i style='font-size:14px;color:#df691a;' class='fa fa-caret-right'></i>&nbsp; Statistički pregledi korištenja";
	$ind026a6="<i style='font-size:14px;color:#df691a;' class='fa fa-caret-right'></i>&nbsp; Izdavanje POS i A4 računa";
	$ind026a7="<i style='font-size:14px;color:#df691a;' class='fa fa-caret-right'></i>&nbsp; Automatski pristup za više klubova";
	$ind026a8="<i style='font-size:14px;color:#df691a;' class='fa fa-caret-right'></i>&nbsp; Dodatni sustav za hotele";
	$ind026b="Za članove";
	$ind026b1="<i style='font-size:14px;color:#df691a;' class='fa fa-caret-right'></i>&nbsp; OnLine pristup rezerviranju";
	$ind026b2="<i style='font-size:14px;color:#df691a;' class='fa fa-caret-right'></i>&nbsp; Rezervacija terena na dodir";
	$ind026b3="<i style='font-size:14px;color:#df691a;' class='fa fa-caret-right'></i>&nbsp; Bez instalacije sustava";
	$ind026b4="<i style='font-size:14px;color:#df691a;' class='fa fa-caret-right'></i>&nbsp; Pregled dosadašnjih rezerviranja";
	$ind026b5="<i style='font-size:14px;color:#df691a;' class='fa fa-caret-right'></i>&nbsp; Uvid u sve novosti kluba i turnire";
	$ind026b6="<i style='font-size:14px;color:#df691a;' class='fa fa-caret-right'></i>&nbsp; Satnica igranja na turniru";
	$ind026b7="<i style='font-size:14px;color:#df691a;' class='fa fa-caret-right'></i>&nbsp; Administracija vlastitih podataka";
	$ind026b8="<i style='font-size:14px;color:#df691a;' class='fa fa-caret-right'></i>&nbsp; Razmjena poruka sa ostalim članovima";
	$ind027a=".";
	$ind028="Za sve klubove i centre, buduće korisnike - prvih 30 dana korištenja je besplatno..";
	$ind029="Registriranjem stječete pravo 30 dana korištenja sustava bez naknade i obveze potpisivanja ugovora.";
	$ind030="Broj članova kluba ";
	$ind031="Najjednostavniji i najbrži sustav rezerviranja.";
	$ind032="Za članove";                                                                                            
	$ind033="Jednostavno korištenje ";
	$ind034="Brzi uvid u rezervacije ";
	$ind035="Rezerviranje jednim klikom ";
	$ind036="Više načina plaćanja rezervacija ";
	$ind037="Pregled vlastitih rezerviranja ";
	$ind038="Administracija vlastitih podataka ";
	$ind039="Pregled troškova rezerviranja ";
	$ind040="Razmjena poruka među članovima ";
	$ind041="Uvid u novosti kluba ";
	$ind042="Uvid u cjenik kluba ";
	$ind043="Usluga dostupna 7 dana / 24 sata";
	$ind044="Online rezervacija sa računala ili mobitela";
	$ind045="Jednostavno administriranje sustavom";
	$ind046="Brza naplata i izdavanje računa";
	$ind047="Automatsko financijsko praćenje";
	$ind048="Brza rezervacija više terena";
	$ind049="Brza rezervacija za duži period";
	$ind050="Evidencija članstva i članarine";
	$ind051="Online unos novosti u radu kluba";
	$ind052="Slanje pozivnica članovima mailom";
	$ind053="Statističko praćenje rezervacija";
	$ind054="Mjesečni računi za članove i tvrtke";
	$ind055="Last minute rezervacije";
	$ind056="Neograničeni broj članova i terena";
	$ind057="Storniranje i otkazivanje terena";
	$ind058="Naknadna naplata terena";
	$ind059="Ostali troškovi korištenja";
	$ind060="Trošak web-servera - € 0.00";
	$ind061="Trošak baze - € 0.00";
	$ind062="Trošak programskih licenci - € 0.00";
	$ind063="Trošak instalacije - € 0.00";
	$ind064="Trošak održavanja sustava - € 0.00";
	$ind084="Trošak arhiviranja podataka - € 0.00";
	$ind085="Trošak nadogradnje sustava - € 0.00";
	$ind086="Trošak prilagodbe Vašem klubu - € 0.00";
	$ind087="Trošak obuke administratora - € 0.00";
	$ind088="Trošak internetskog prometa - € 0.00";
	$ind066="Ugovor bez klauzule trajanja ";
	$ind067="Neograničen broj članova ";
	$ind068="Nema dodatnih troškova ";
	$ind069="Minimalani troškovi najma ";
	$ind070="Online podrška korisnicima ";
	$ind071="Besplatna nadogradnja sustava ";
	$ind072="Eliminacija 99% telefonskih poziva ";
	$ind073="Eliminacija papirnog vođenja ";
	$ind074="Eliminacija dvostrukog rezerviranja ";
	$ind075="Dosadašnje zadovoljstvo korisnika ";
	$ind076="Registracija";
	$ind077="Pitanja";
	$ind078="NOVO!";
	$ind079="Optimizirano za";
	$ind080="SPORTBOOKING sustav rezervacija možete koristiti bez bilo kakvih ograničenja, bez vremenske ugovorne obveze uz stalnu dostupnost 7/24.";
	$ind081="Kao podrška sustavu na raspolaganju su Vam slijedeće mogućnosti komunikacije";
	$ind082="Za klubove";
	$ind083="Ostale pogodnosti";
	$ind089="AKCIJSKA CIJENA - ZA PRIJAVE I POČETAK KORIŠTENAJ SUSTAVA DO 30.06.2020. godine";
	$ind090="MJESEČNA NAKNADA - € 8,00 ( + pdv ) PO TERENU.";
	$ind090a="Cijena od 01.07.2020. godine - MJESEČNA NAKNADA - € 9,90 ( + pdv ) PO TERENU.";
	$ind091="Mjesečna naknada za korištenje terena obuhvaća licencu za jedan klub sa pravom neograničenog korištenja sustava.";
	$ind092="Svi ostali troškovi koji proizlaze korištenjem sustava za Vas su besplatni.";
	$ind093="U prvom mjesecu korištenja sustava omogućavamo Vam da detaljno provjerite kvalitetu sustava i isprobate sve opcije koje su vam na raspolaganju BESPLATNO.";
	$ind093a="<br><i style='color:#df691a;' class='fa fa-caret-right'></i> Do kraja prvih 30 dana korištenja potrebno je potpisati ugovor o korištenju sustava, pravima i obvezama ili odustati od korištenja.";
	$ind094="Registracijom stječete pravo na 30 dana besplatnog korištenja sustava rezervacija.";
	$ind095="Naziv kluba";
	$ind096="Mjesto";
	$ind097="Poštanski broj";
	$ind098="Ulica i kućni broj";
	$ind099="Ovlaštena osoba";
	$ind100="E-mail adresa";
	$ind101="Kontakt telefon";
	$ind102="Država";
	$ind103="Registraciju popunjavaju isključivo klubovi.";
	$ind104="Članovi sportskog centra se prijavljuju svom administratoru centra.";
	$ind105="Budite i Vi dio najveće sportske mreže!";
	$ind106="Potrebno je popuniti sve podatke.";
	$ind107="Zahvaljujemo na registraciji !";
	$ind107a="U roku od 24 sata poslati ćemo na Vaš mail podatke o pristupu sustavu.";
	$ind108="Moguća komunikacija sa našim administratorima";
	$ind109="Odaberi jezik";
	$ind110="Češki";
	$ind111="Engleski";
	$ind112="Francuski";
	$ind113="Hrvatski";
	$ind114="Mađarski";
	$ind115="Nizozemski";
	$ind116="Njemački";
	$ind117="Poljski";
	$ind118="Portugalski";
	$ind119="Srpski";
	$ind120="Španjolski";
	$ind121="Talijanski";
	$ind122="© 2015 CSH d.o.o.";
	$ind123="Sportbooking";
	$ind123a="Sportbooking - Cjenik";
	$ind123b="Sportbooking - Kontakt";
	$ind123c="Sportbooking - Prednosti";
	$ind123d="Sportbooking - Registracija";
	$ind123e="Sportbooking";
	$ind123f="Sportbooking";
	$ind124="SPORTBOOKING";
	$ind125="Prednosti Sportbooking sustava za rezervacije terena";
	$ind126="Upišite svoje korisničko ime";
	$ind127="Upišite svoju zaporku";
	$ind128="Za sve korisnike koji se prijave do 31.03.2015. godine";
	$ind129="Prijava u sustav";
	$ind130="Prednosti sustava";
	$ind131="Po registraciji će Vas kontaktirati naš administrator.";
	$ind132="Prijavi se";
	$ind133="Sva prava pridržana";
	$ind134="C.S.H. d.o.o.";
	$ind135="Sportbooking v3.0.001";
	$ind136="PRIJAVA NEUSPJEŠNA !";
	$ind137="Generalni sponzor";
} elseif($oklen=="DE" or $oklen=="AT" or $oklen=="CH" or $oklen=="LI" or $oklen=="LU"){
	$naslov="Sustav za rezervaciju sportskih terena";
	$drzava="images/cro2.png";
	$ind001="Korisničko ime i zaporka nisu ispravni ili je administrator zabranio pristup.";
	$ind002="Korisničko ime i zaporka se ne podudaraju. Probajte ponovo ili provjerite kod tajnika kluba.";
	$ind003="Popunite korisničko ime i zaporku.";
	$ind004="Korisničko ime";
	$ind004a="Upiši Vaše korisničko ime";
	$ind005="Pritisnuti za ulaz u sustav za registrirane korisnike";
	$ind006="Zaporka";
	$ind006a="Upiši Vašu zaporku";
	$ind007="Prijava";
	$ind020="Polazna";
	$ind021="Registriraj se";
	$ind022="Cjenik";
	$ind022a="Pogodnosti";
	$ind022b="Prednosti";
	$ind023="Kontakt";
	$ind024="Izvrši prijavu";
	$ind025="Pogodnosti Sportbooking sustava rezervacija sportskih terena:";
	$ind026a="Za klubove";
	$ind026a1="<i style='font-size:14px;color:#df691a;' class='fa fa-caret-right'></i>&nbsp; Snažan alat za upravljanje klubom i terenima";
	$ind026a2="<i style='font-size:14px;color:#df691a;' class='fa fa-caret-right'></i>&nbsp; Trenutni uvid (ne)zauzetosti sportskih terena";
	$ind026a3="<i style='font-size:14px;color:#df691a;' class='fa fa-caret-right'></i>&nbsp; Evidencija i vođenje članstva";
	$ind026a4="<i style='font-size:14px;color:#df691a;' class='fa fa-caret-right'></i>&nbsp; Naplata korištenja terena";
	$ind026a5="<i style='font-size:14px;color:#df691a;' class='fa fa-caret-right'></i>&nbsp; Statistički pregledi korištenja";
	$ind026a6="<i style='font-size:14px;color:#df691a;' class='fa fa-caret-right'></i>&nbsp; Izdavanje POS i A4 računa";
	$ind026a7="<i style='font-size:14px;color:#df691a;' class='fa fa-caret-right'></i>&nbsp; Automatski pristup za više klubova";
	$ind026a8="<i style='font-size:14px;color:#df691a;' class='fa fa-caret-right'></i>&nbsp; Dodatni sustav za hotele";
	$ind026b="Za članove";
	$ind026b1="<i style='font-size:14px;color:#df691a;' class='fa fa-caret-right'></i>&nbsp; OnLine pristup rezerviranju";
	$ind026b2="<i style='font-size:14px;color:#df691a;' class='fa fa-caret-right'></i>&nbsp; Rezervacija terena na dodir";
	$ind026b3="<i style='font-size:14px;color:#df691a;' class='fa fa-caret-right'></i>&nbsp; Bez instalacije sustava";
	$ind026b4="<i style='font-size:14px;color:#df691a;' class='fa fa-caret-right'></i>&nbsp; Pregled dosadašnjih rezerviranja";
	$ind026b5="<i style='font-size:14px;color:#df691a;' class='fa fa-caret-right'></i>&nbsp; Uvid u sve novosti kluba i turnire";
	$ind026b6="<i style='font-size:14px;color:#df691a;' class='fa fa-caret-right'></i>&nbsp; Satnica igranja na turniru";
	$ind026b7="<i style='font-size:14px;color:#df691a;' class='fa fa-caret-right'></i>&nbsp; Administracija vlastitih podataka";
	$ind026b8="<i style='font-size:14px;color:#df691a;' class='fa fa-caret-right'></i>&nbsp; Razmjena poruka sa ostalim članovima";
	$ind027a=".";
	$ind028="Za sve klubove i centre, buduće korisnike - prvih 30 dana korištenja je besplatno..";
	$ind029="Registriranjem stječete pravo 30 dana korištenja sustava bez naknade i obveze potpisivanja ugovora.";
	$ind030="Broj članova kluba ";
	$ind031="Najjednostavniji i najbrži sustav rezerviranja.";
	$ind032="Za članove";                                                                                            
	$ind033="Jednostavno korištenje ";
	$ind034="Brzi uvid u rezervacije ";
	$ind035="Rezerviranje jednim klikom ";
	$ind036="Više načina plaćanja rezervacija ";
	$ind037="Pregled vlastitih rezerviranja ";
	$ind038="Administracija vlastitih podataka ";
	$ind039="Pregled troškova rezerviranja ";
	$ind040="Razmjena poruka među članovima ";
	$ind041="Uvid u novosti kluba ";
	$ind042="Uvid u cjenik kluba ";
	$ind043="Usluga dostupna 7 dana / 24 sata";
	$ind044="Online rezervacija sa računala ili mobitela";
	$ind045="Jednostavno administriranje sustavom";
	$ind046="Brza naplata i izdavanje računa";
	$ind047="Automatsko financijsko praćenje";
	$ind048="Brza rezervacija više terena";
	$ind049="Brza rezervacija za duži period";
	$ind050="Evidencija članstva i članarine";
	$ind051="Online unos novosti u radu kluba";
	$ind052="Slanje pozivnica članovima mailom";
	$ind053="Statističko praćenje rezervacija";
	$ind054="Mjesečni računi za članove i tvrtke";
	$ind055="Last minute rezervacije";
	$ind056="Neograničeni broj članova i terena";
	$ind057="Storniranje i otkazivanje terena";
	$ind058="Naknadna naplata terena";
	$ind059="Ostali troškovi korištenja";
	$ind060="Trošak web-servera - € 0.00";
	$ind061="Trošak baze - € 0.00";
	$ind062="Trošak programskih licenci - € 0.00";
	$ind063="Trošak instalacije - € 0.00";
	$ind064="Trošak održavanja sustava - € 0.00";
	$ind084="Trošak arhiviranja podataka - € 0.00";
	$ind085="Trošak nadogradnje sustava - € 0.00";
	$ind086="Trošak prilagodbe Vašem klubu - € 0.00";
	$ind087="Trošak obuke administratora - € 0.00";
	$ind088="Trošak internetskog prometa - € 0.00";
	$ind066="Ugovor bez klauzule trajanja ";
	$ind067="Neograničen broj članova ";
	$ind068="Nema dodatnih troškova ";
	$ind069="Minimalani troškovi najma ";
	$ind070="Online podrška korisnicima ";
	$ind071="Besplatna nadogradnja sustava ";
	$ind072="Eliminacija 99% telefonskih poziva ";
	$ind073="Eliminacija papirnog vođenja ";
	$ind074="Eliminacija dvostrukog rezerviranja ";
	$ind075="Dosadašnje zadovoljstvo korisnika ";
	$ind076="Registracija";
	$ind077="Pitanja";
	$ind078="NOVO!";
	$ind079="Optimizirano za";
	$ind080="SPORTBOOKING sustav rezervacija možete koristiti bez bilo kakvih ograničenja, bez vremenske ugovorne obveze uz stalnu dostupnost 7/24.";
	$ind081="Kao podrška sustavu na raspolaganju su Vam slijedeće mogućnosti komunikacije";
	$ind082="Za klubove";
	$ind083="Ostale pogodnosti";
	$ind089="AKCIJSKA CIJENA - ZA PRIJAVE I POČETAK KORIŠTENAJ SUSTAVA DO 30.06.2020. godine";
	$ind090="MJESEČNA NAKNADA - € 8,00 ( + pdv ) PO TERENU.";
	$ind090a="Cijena od 01.07.2020. godine - MJESEČNA NAKNADA - € 9,90 ( + pdv ) PO TERENU.";
	$ind091="Mjesečna naknada za korištenje terena obuhvaća licencu za jedan klub sa pravom neograničenog korištenja sustava.";
	$ind092="Svi ostali troškovi koji proizlaze korištenjem sustava za Vas su besplatni.";
	$ind093="U prvom mjesecu korištenja sustava omogućavamo Vam da detaljno provjerite kvalitetu sustava i isprobate sve opcije koje su vam na raspolaganju BESPLATNO.";
	$ind093a="<br><i style='color:#df691a;' class='fa fa-caret-right'></i> Do kraja prvih 30 dana korištenja potrebno je potpisati ugovor o korištenju sustava, pravima i obvezama ili odustati od korištenja.";
	$ind094="Registracijom stječete pravo na 30 dana besplatnog korištenja sustava rezervacija.";
	$ind095="Naziv kluba";
	$ind096="Mjesto";
	$ind097="Poštanski broj";
	$ind098="Ulica i kućni broj";
	$ind099="Ovlaštena osoba";
	$ind100="E-mail adresa";
	$ind101="Kontakt telefon";
	$ind102="Država";
	$ind103="Registraciju popunjavaju isključivo klubovi.";
	$ind104="Članovi sportskog centra se prijavljuju svom administratoru centra.";
	$ind105="Budite i Vi dio najveće sportske mreže!";
	$ind106="Potrebno je popuniti sve podatke.";
	$ind107="Zahvaljujemo na registraciji !";
	$ind107a="U roku od 24 sata poslati ćemo na Vaš mail podatke o pristupu sustavu.";
	$ind108="Moguća komunikacija sa našim administratorima";
	$ind109="Odaberi jezik";
	$ind110="Češki";
	$ind111="Engleski";
	$ind112="Francuski";
	$ind113="Hrvatski";
	$ind114="Mađarski";
	$ind115="Nizozemski";
	$ind116="Njemački";
	$ind117="Poljski";
	$ind118="Portugalski";
	$ind119="Srpski";
	$ind120="Španjolski";
	$ind121="Talijanski";
	$ind122="© 2015 CSH d.o.o.";
	$ind123="Sportbooking";
	$ind123a="Sportbooking - Cjenik";
	$ind123b="Sportbooking - Kontakt";
	$ind123c="Sportbooking - Prednosti";
	$ind123d="Sportbooking - Registracija";
	$ind123e="Sportbooking";
	$ind123f="Sportbooking";
	$ind124="SPORTBOOKING";
	$ind125="Prednosti Sportbooking sustava za rezervacije terena";
	$ind126="Upišite svoje korisničko ime";
	$ind127="Upišite svoju zaporku";
	$ind128="Za sve korisnike koji se prijave do 31.03.2015. godine";
	$ind129="Prijava u sustav";
	$ind130="Prednosti sustava";
	$ind131="Po registraciji će Vas kontaktirati naš administrator.";
	$ind132="Prijavi se";
	$ind133="Sva prava pridržana";
	$ind134="C.S.H. d.o.o.";
	$ind135="Sportbooking v3.0.001";
	$ind136="PRIJAVA NEUSPJEŠNA !";
	$ind137="Generalni sponzor";
} else {
	$naslov="Sport Reservation System";
	$drzava="images/gb.png";
	$ind001="Username and password incorrect or administrator denied access.";
	$ind002="Username and password do not match. Please try again or check with the club secretary.";
	$ind003="Enter your username and password.";
	$ind004="Username";
	$ind004a="Enter your username";
	$ind005="Press this button to enter the system";
	$ind006="Password";
	$ind006a="Enter your password";
	$ind007="Log in";
	$ind020="Home";
	$ind021="Registration";
	$ind022="Price list";
	$ind022a="Benefits";
	$ind022b="Advantages";
	$ind023="Contact";
	$ind024="Log in";
	$ind025="Benefits of Sport Reservation System:";
	$ind026a="For sports centers";
	$ind026a1="<i style='font-size:14px;color:#df691a;' class='fa fa-caret-right'></i>&nbsp; A powerful management tool for the club and courtsa";
	$ind026a2="<i style='font-size:14px;color:#df691a;' class='fa fa-caret-right'></i>&nbsp; Trenutni uvid (ne)zauzetosti sportskih terena";
	$ind026a3="<i style='font-size:14px;color:#df691a;' class='fa fa-caret-right'></i>&nbsp; Issuance of POS and Bills";
	$ind026a4="<i style='font-size:14px;color:#df691a;' class='fa fa-caret-right'></i>&nbsp; No software to install";
	$ind026a5="<i style='font-size:14px;color:#df691a;' class='fa fa-caret-right'></i>&nbsp; Very easy set up and integration with your website";
	$ind026a6="<i style='font-size:14px;color:#df691a;' class='fa fa-caret-right'></i>&nbsp; Quickly update availability for each time unit";
	$ind026a7="<i style='font-size:14px;color:#df691a;' class='fa fa-caret-right'></i>&nbsp; Charges for use of the courts";
	$ind026a8="<i style='font-size:14px;color:#df691a;' class='fa fa-caret-right'></i>&nbsp; Statistics for members and admin";
	$ind026b="For members";
	$ind026b1="<i style='font-size:14px;color:#df691a;' class='fa fa-caret-right'></i>&nbsp; OnLine reservation access";
	$ind026b2="<i style='font-size:14px;color:#df691a;' class='fa fa-caret-right'></i>&nbsp; Court reservation with one touch";
	$ind026b3="<i style='font-size:14px;color:#df691a;' class='fa fa-caret-right'></i>&nbsp; Printable invoices";
	$ind026b4="<i style='font-size:14px;color:#df691a;' class='fa fa-caret-right'></i>&nbsp; Bookings for multiple days";
	$ind026b5="<i style='font-size:14px;color:#df691a;' class='fa fa-caret-right'></i>&nbsp; No system installation";
	$ind026b6="<i style='font-size:14px;color:#df691a;' class='fa fa-caret-right'></i>&nbsp; Overview of reservations to date";
	$ind026b7="<i style='font-size:14px;color:#df691a;' class='fa fa-caret-right'></i>&nbsp; Administering your own data";
	$ind026b8="<i style='font-size:14px;color:#df691a;' class='fa fa-caret-right'></i>&nbsp; Messaging with other members";
	$ind027a=".";
	$ind028="For all clubs and centers - first 30 days of use is free";
	$ind029="By registering you will be entitled 30 days of using the system free of charge and obligations of signing the contract.";
	$ind030="Number of club members ";
	$ind031="The simplest and fastest tennis court reservation system.";
	$ind032="For members";                                                                                            
	$ind033="Easy to use ";
	$ind034="A quick review at reserved courts ";                  
	$ind035="One Click Reservation ";                        
	$ind036="More ways to pay for reservations ";            
	$ind037="Reviewing your own bookings ";                  
	$ind038="Administering your own data ";                  
	$ind039="Booking Cost Review ";                          
	$ind040="Messaging among members ";                      
	$ind041="Insights into the club's news ";                
	$ind042="Club Price List review ";                     
	$ind043="Service Available 7 Days / 24 Hours ";          
	$ind044="Online booking from a PC or cellphone ";  
	$ind045="Easy System Administration ";                   
	$ind046="Fast billing and invoicing ";                   
	$ind047="Automatic Financial Tracking ";                 
	$ind048="Fast multi-court booking ";                   
	$ind049="Quick Long Term Booking ";                      
	$ind050="Membership and membership records ";            
	$ind051="Online news feed for the club ";                
	$ind052="Send invitations to members by mail ";          
	$ind053="Statistical tracking of bookings ";             
	$ind054="Monthly Members & Business Accounts ";          
	$ind055="Last Minute Reservations ";                     
	$ind056="Unlimited members and pitch ";                  
	$ind057="Reversal and Cancellation of Terrain ";         
	$ind058="Postpay Billing ";                              
	$ind059="Other Usage Costs ";                   
	$ind060="Web server cost - € 0.00 ";            
	$ind061="Base Cost - € 0.00 ";                  
	$ind062="Program License Cost - € 0.00 ";       
	$ind063="Installation Cost - € 0.00 ";          
	$ind064="System Maintenance Cost - € 0.00 ";    
	$ind084="Cost of archiving data - € 0.00 ";     
	$ind085="System upgrade cost - € 0.00 ";        
	$ind086="Cost to adjust to your club - € 0.00 ";
	$ind087="Administrator Training Cost - € 0.00 ";
	$ind088="Internet traffic cost - € 0.00 ";      
	$ind066="Contract with no duration clause ";    
	$ind067="Unlimited members ";                   
	$ind068="No additional costs ";                 
	$ind069="Minimum rental costs ";                
	$ind070="Online Customer Support ";             
	$ind071="Free System Upgrade ";                 
	$ind072="Eliminating 99% of Phone Calls ";      
	$ind073="Elimination of Paper Guidance ";       
	$ind074="Double booking elimination ";          
	$ind075="Customer Satisfaction ";               
	$ind076="Registration";
	$ind077="Questions";
	$ind078="New !";
	$ind079="Optimized for";
	$ind080="You can use the SPORTBOOKING booking system without any restrictions, without a time contractual obligation, with constant availability 7/24.";
	$ind081="The following communication options are available to support the system";
	$ind082="For Sports centre";
	$ind083="Rest of benefits";
	$ind089="ACTION PRICE - FOR REGISTRATION AND BEGINNING USE OF THE SYSTEM BY 30.06.2020. years";
	$ind090="MONTHLY FEE - € 8,00 (+ VAT) PER COURT.<br>";
	$ind090a="Price from 07/01/2020. year - MONTHLY FEE - € 9,90 (+ VAT) PER COURT.<br>";
	$ind091="The monthly fee for use of the courts includes a license for a club with the right to unlimited use of the system.";
	$ind092="All other costs incurred by using the system are free of charge to you.";
	$ind093="During the first month of using the system, we allow you to thoroughly check the quality of the system and try out all the options available to you for FREE.";
	$ind093a="<br><i style='color:#df691a;' class='fa fa-caret-right'></i> By the end of the first 30 days of use, it is necessary to sign a contract on the use of the system, rights and obligations or to cancel the use.";
	$ind094="By registering you are entitled to 30 days free use of the reservation system.";
	$ind095="Name of sports centre";
	$ind096="City";
	$ind097="Postal code";
	$ind098="Address";
	$ind099="contact person";
	$ind100="E-mail";
	$ind101="Phone";
	$ind102="State";
	$ind103="Registration filled only official person of sports center.";
	$ind104="Members of the sports center register by their center administrator.";
	$ind105="Be a part of the largest sports network !";
	$ind106="It is necessary to fill in all the information.";
	$ind107="Thank you for registering !";
	$ind107a="We will send your system access information to your mail within 24 hours.";
	$ind108="Possible communication with our administrators";
	$ind109="Choose your language";
	$ind110="Czech";     
	$ind111="English";   
	$ind112="French";    
	$ind113="Croatian";  
	$ind114="Hungarian ";
	$ind115="Dutch ";    
	$ind116="German";    
	$ind117="Polish";    
	$ind118="Portuguese";
	$ind119="Serbian";   
	$ind120="Spanish ";  
	$ind121="Italian";   
	$ind122="© 2015 CSH d.o.o.";
	$ind123="Sportbooking";
	$ind123a="Sportbooking - Price list";
	$ind123b="Sportbooking - Contact";
	$ind123c="Sportbooking - Benefits";
	$ind123d="Sportbooking - Registration";
	$ind123e="Sportbooking";
	$ind123f="Sportbooking";
	$ind124="SPORTBOOKING";
	$ind125="Prednosti Sportbooking sustava za rezervacije terena";
	$ind126="Enter your username";
	$ind127="Enter your password";
	$ind128="For all centers who sign up by 31.06.2020. years";
	$ind129="Log in";
	$ind130="SRS - features";
	$ind131="After registration will contact You our administrator.";
	$ind132="Login";
	$ind133="All rights reserved";
	$ind134="C.S.H. Ltd.";
	$ind135="Sportbooking v3.0.001";
	$ind136="LOGIN UNSUCCESSFUL !";
	$ind137="General sponsor";
}
$ind138="";
$ind139="";
?>